Change nav bar dark mode
Backbone-UTP/main-page pull request #18
Opened 2024-09-13 05:34 UTC by JGaviria0

- Change nav bar color in dark mode
- Change hover strategy, the old one change color to yellow, now scale up. 
- Delete "Patrocinadores" tap

2024-09-14 01:59 UTC, Djkde01 requested changes

2024-09-14 01:59 UTC, Djkde01 commented on src/app/pages/events/sfd-2024/components/header/header.component.html
![image](https://github.com/user-attachments/assets/7465ef8d-3adb-4eba-8def-54ec23e70ae4)
Al iniciar la página, el contraste de los elementos del navbar no es la adecuada

2024-09-14 18:02 UTC, JGaviria0 commented on src/app/pages/events/sfd-2024/components/header/header.component.html
@Djkde01  ahí le dejo.

2024-09-16 17:52 UTC, paulacastro1 approved these changes

2024-09-16 17:56 UTC, Djkde01 approved these changes

2024-09-16 17:56 UTC, merged