presentation card in dark mode
Backbone-UTP/main-page pull request #20
Opened 2024-09-13 06:15 UTC by JGaviria0

- Change sonar foto. 
- Change colors to presentation car in dark mode

2024-09-13 06:22 UTC, JGaviria0 commented
Hace falta el pr de los circulos para acomodar un poco mejor el color.

2024-09-14 01:54 UTC, Djkde01 requested changes

2024-09-14 01:54 UTC, Djkde01 commented on src/assets/images/speakers/SONAR ISC.png
Se podrá conseguir una imagen con fondo transparente?

2024-09-14 01:55 UTC, Djkde01 commented
> Hace falta el pr de los circulos para acomodar un poco mejor el color.

https://github.com/Backbone-UTP/main-page/issues/10

Ya está merge con `sfd-landing` actualizar cambios

2024-09-14 04:35 UTC, JGaviria0 commented on src/app/pages/events/sfd-2024/components/card-presentation/card-presentation.component.ts
> +  public circlesStyle = 'border-[#424242] dark:border-[#cab9b6]';
@MiguelCano-ia Tener en cuenta que tailwind solo importa los componentes que necesita, eso quiere decir que el no conoce algo como border-[{{variable}}] porque el no sabe que variable es, por otro lado tambien esta mirando los archivos de js por eso esto si se puede hacer, border-[#000] ya que sabe que debe importar ese elemento. 

Podemos revisar mas la proxima clase.

2024-09-15 01:06 UTC, MiguelCano-ia commented on src/app/pages/events/sfd-2024/components/card-presentation/card-presentation.component.ts
> +  public circlesStyle = 'border-[#424242] dark:border-[#cab9b6]';
R

2024-09-16 17:49 UTC, DiegoRangel187 approved these changes

2024-09-16 17:51 UTC, paulacastro1 approved these changes

2024-09-16 17:56 UTC, Djkde01 approved these changes

2024-09-16 17:56 UTC, merged