Fix-11
Backbone-UTP/main-page pull request #22
Opened 2024-09-14 02:47 UTC by SydMatters

Update of hover time line titles

2024-09-14 03:51 UTC, JGaviria0 approved these changes
LGTM (Looks Good To Me)

2024-09-14 17:38 UTC, Djkde01 requested changes

2024-09-14 17:38 UTC, Djkde01 commented on src/app/shared/components/timeline/timeline.component.html
> +      <div class=" hover:scale-110 duration-700 transition-transform cursor-pointer sticky top-0" *ngIf="i % 2 == 0" (click)="openModal(item)">
Mantener consistencia de escalas (scale-105)
Se pueden ver ejemplos en `src/app/shared/components/logos-list/logos-list.component.html` y en `src/app/shared/components/profile-card/profile-card.component.html`

2024-09-16 17:37 UTC, Djkde01 commented on src/app/shared/components/timeline/timeline.component.html
> +      <div class=" hover:scale-110 duration-700 transition-transform cursor-pointer sticky top-0" *ngIf="i % 2 == 0" (click)="openModal(item)">
Convertido a issue, para arreglar en futuro despliegue

https://github.com/Backbone-UTP/main-page/issues/29

2024-09-16 17:37 UTC, merged