temporaly change redirect / and /main path
Backbone-UTP/main-page pull request #27
Opened 2024-09-14 06:17 UTC by JGaviria0

- Redirect / and /main to sfd page

2024-09-14 18:05 UTC, paulacastro1 submitted a review, later dismissed

2024-09-16 02:05 UTC, Djkde01 requested changes

2024-09-16 02:05 UTC, Djkde01 commented on src/app/app-routing.module.ts
> +    //   import('./pages/main/main.module').then((m) => m.MainModule),
Eliminar código comentado

2024-09-16 14:34 UTC, Djkde01 approved these changes

2024-09-16 14:58 UTC, paulacastro1 approved these changes

2024-09-16 15:09 UTC, merged