fix agenda, redirect tag, buttons
Backbone-UTP/main-page pull request #6
Opened 2024-09-03 05:37 UTC by JGaviria0

fix agenda, redirect tag, buttons
Delete call to acction to exponsors and speakers.

2024-09-03 17:34 UTC, Djkde01 requested changes

2024-09-03 17:34 UTC, Djkde01 commented on src/assets/content/sfd-features.ts
> +  },
Ya que estamos advirtiendo al inicio de la sección que la agenda estará sujeta a cambios, estos eventos no son necesarios.

2024-09-03 17:34 UTC, Djkde01 commented on src/app/pages/events/sfd-2024/components/hero/hero.component.html
> +        text="Acerca del evento mundial"
Cambiar el título por algo más corto y conciso. Estilo "SFD en el mundo"

2024-09-03 17:35 UTC, Djkde01 commented on src/app/pages/events/sfd-2024/components/hero/hero.component.html
> +        text="Acerca del evento mundial"
También se puede considerar si este botón va acá, o poner el enlace en otro lado.
Ya que en el Hero se pondrán los logos de GitHub y Backbone

2024-09-03 21:59 UTC, JGaviria0 commented on src/assets/content/sfd-features.ts
> +  },
Pero se ve mal que en media hora no pase nada, y también para los que están viendo la agenda antes de que sepan que falta una charla.

2024-09-03 22:01 UTC, JGaviria0 commented on src/app/pages/events/sfd-2024/components/hero/hero.component.html
> +        text="Acerca del evento mundial"
Solved: por ahora siento que queda desbalanceado si quitamos el botón.

2024-09-04 17:39 UTC, Djkde01 commented on src/assets/content/sfd-features.ts
> +  },
Por eso se hace la aclaración que la agenda va a cambiar.
Una vez se confirme, ponemos el evento y quitamos el aviso

2024-09-04 20:42 UTC, Djkde01 approved these changes

2024-09-04 20:46 UTC, DiegoRangel187 approved these changes

2024-09-04 20:46 UTC, merged